# Generated by Django 4.2.7 on 2024-02-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_pay_url_payment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='id продукта'),
        ),
    ]
