# Generated by Django 4.2.7 on 2024-02-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Курсы', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['name', 'course_lesson'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
